[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim']
hook_add = '''
  " Use the platinum searcher
  call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
  call denite#custom#var('grep', 'command', ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
  call denite#custom#var('grep', 'default_opts', [])
  call denite#custom#var('grep', 'recursive_opts', [])

  " Prefix key
  nnoremap [denite] <Nop>
  nmap <Space>d [denite]

  nmap <silent> [denite]p :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  nmap <silent> [denite]b :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
  nmap <silent> [denite]g :<C-u>Denite grep -highlight-mode-insert=Search<CR>
  nmap <silent> [denite]o :<C-u>Denite outline -highlight-mode-insert=Search<CR>
  nmap <silent> [denite]r :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
  nmap <silent> [denite]h :<C-u>Denite command_history -highlight-mode-insert=Search<CR>

  nmap <silent> [denite]] :<C-u>DeniteCursorWord grep -highlight-mode-insert=Search<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

