[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim']
hook_add = '''
  " Prefix key
  nnoremap [denite] <Nop>
  nmap <Space>d [denite]
  " Current direcotry files
  nmap <silent> [denite]p :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  " Buffer files
  nmap <silent> [denite]b :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
  " Reccent file
  nmap <silent> [denite]r :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
  " Command history
  nmap <silent> [denite]h :<C-u>Denite command_history -highlight-mode-insert=Search<CR>
  " Grep
  nmap <silent> [denite]g :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimproc']
hook_add = '''
  let g:unite_enable_start_insert = 0
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  let g:unite_split_rule = 'botright'
'''

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite']
hook_add = '''
  nnoremap <silent> [denite]o :Denite unite:outline<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make CC=gcc'
'''

