[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_post_update = '''
  make install
'''
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_folding_level = 6
  let g:vim_markdown_no_default_key_mappings = 1
  let g:vim_markdown_toc_autofit = 1
  let g:vim_markdown_conceal = 1
  let g:vim_markdown_fenced_languages = [
    \ 'ini=dosini'
  \ ]
  let g:vim_markdown_math = 1
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_toml_frontmatter = 1
  let g:vim_markdown_json_frontmatter = 1
  let g:vim_markdown_strikethrough = 1
  let g:vim_markdown_new_list_item_indent = 2
'''
hook_add = '''
  " Prefix key
  nnoremap [markdown] <Nop>
  nmap <Space>m [markdown]

  nmap <silent> [markdown]n <Plug>Markdown_MoveToNextHeader
  nmap <silent> [markdown]p <Plug>Markdown_MoveToPreviousHeader
  nmap <silent> [markdown]c <Plug>Markdown_MoveToCurHeader
  nmap <silent> [markdown]u <Plug>Markdown_MoveToParentHeader
  nmap <silent> [markdown]v :<C-u>Tocv<CR>
  nmap <silent> [markdown]h :<C-u>Toch<CR>
'''

