[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/fzf'
build = '''
  ./install --bin
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)
  command! -bang -nargs=? -complete=dir HFiles
    \ call fzf#vim#files(<q-args>, {'source': 'rg --hidden --files', 'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)
  command! -bang -nargs=? -complete=dir GFiles
    \ call fzf#vim#gitfiles(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1,
    \   fzf#vim#with_preview(), <bang>0)
  command! -bang -nargs=* RgHidden
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case --hidden ".shellescape(<q-args>), 1,
    \   fzf#vim#with_preview(), <bang>0)

  " Prefix key
  nnoremap [fzf] <Nop>
  nmap <Space>f [fzf]

  nmap <silent> [fzf]b :<C-u>Buffers<CR>
  nmap <silent> [fzf]c :<C-u>Commands<CR>
  nmap <silent> [fzf]f :<C-u>Files<CR>
  nmap <silent> [fzf]F :<C-u>HFiles<CR>
  nmap <silent> [fzf]g :<C-u>Rg<CR>
  nmap <silent> [fzf]G :<C-u>RgHidden<CR>
  nmap <expr> [fzf]G/ ':<C-u>RgHidden '.expand('<cword>').'<CR>'
  nmap <silent> [fzf]h :<C-u>History<CR>
  nmap <silent> [fzf]H: :<C-u>History:<CR>
  nmap <silent> [fzf]H/ :<C-u>/History<CR>
  nmap <silent> [fzf]m :<C-u>Marks<CR>
  nmap <silent> [fzf]p :<C-u>GFiles<CR>
  nmap <silent> [fzf]t :<C-u>Tags<CR>
  nmap <silent> [fzf]T :<C-u>BTags<CR>
  nmap <silent> [fzf]l :<C-u>Lines<CR>
  nmap <silent> [fzf]L :<C-u>BLines<CR>
  nmap <expr> [fzf]/ ':<C-u>Rg '.expand('<cword>').'<CR>'
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
build = '''
  ./install.sh nightly
'''
hook_add = '''
  set hidden
  set nobackup
  set nowritebackup

  set cmdheight=2
  set updatetime=300
  set shortmess+=c
  set signcolumn=yes

  " Prefix key
  nnoremap [coc] <Nop>
  nmap <Space>l [coc]

  xmap <silent> [coc]a <Plug>(coc-codeaction-selected)
  nmap <silent> [coc]a <Plug>(coc-codeaction-selected)
  nmap <silent> [coc]A <Plug>(coc-codeaction)
  nmap <silent> [coc]d <Plug>(coc-definition)
  nmap <silent> [coc]f :call CocAction('format')<CR>
  nmap <silent> [coc]F <Plug>(coc-fix-current)
  nmap <silent> [coc]i <Plug>(coc-implementation)
  nnoremap <silent> [coc]j :<C-u>CocNext<CR>
  nnoremap <silent> [coc]k :<C-u>CocPrev<CR>
  nnoremap <silent> [coc]Lc :<C-u>CocList commands<CR>
  nnoremap <silent> [coc]Ld :<C-u>CocList diagnostics<CR>
  nnoremap <silent> [coc]Le :<C-u>CocList extensions<CR>
  nnoremap <silent> [coc]Lo :<C-u>CocList outline<CR>
  nnoremap <silent> [coc]Ls :<C-u>CocList -I symbols<CR>
  nmap <silent> [coc]n <Plug>(coc-rename)
  nnoremap <silent> [coc]p :<C-u>CocListResume<CR>
  nmap <silent> [coc]r <Plug>(coc-references)
  nmap <silent> [coc]y <Plug>(coc-type-definition)
  nmap <silent> [coc][ <Plug>(coc-diagnostic-prev)
  nmap <silent> [coc]] <Plug>(coc-diagnostic-next)

  nnoremap <silent> [coc]K :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    if &filetype == 'vim'
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction

  " Highlight symbol under cursor on CursorHold
  autocmd CursorHold * silent call CocActionAsync('highlight')
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  set diffopt=vertical

  nnoremap [fugitive]  <Nop>
  nmap <space>g [fugitive]

  nnoremap <silent> [fugitive]s :Gstatus<CR>
  nnoremap <silent> [fugitive]a :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]m :Gmerge<CR>
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  autocmd! VimEnter * nested colorscheme molokai
'''

