[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1
on_ft = ['python']

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']
hook_source = '''
  " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  " エラー表示の列を常時表示
  let g:ale_sign_column_always = 1
  " ファイルを開いたときにlint実行
  let g:ale_lint_on_enter = 1
  " ファイルを保存したときにlint実行
  let g:ale_lint_on_save = 1
  " 編集中のlintはしない
  let g:ale_lint_on_text_changed = 'never'
  " lint結果をロケーションリストとQuickFixには表示しない
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0
  " 有効にするlinters & fixers
  let g:ale_linters = { 'python': ['flake8'] }
  let g:ale_fixers = {
    \ 'python': ['autopep8', 'black', 'isort']
  \ }
'''
hook_add = '''
  " Prefix key
  nnoremap [ale] <Nop>
  nmap <Space>a [ale]
  " エラー行にジャンプ
  nmap <silent> [ale]p :<C-u>ALEPreviousWrap<CR>
  nmap <silent> [ale]n :<C-u>ALENextWrap<CR>
  nmap <silent> [ale]f :<C-u>ALEFix<CR>
'''

